export const flyerConfig = {
  organisationName: "RCCG The Bridge Chicago",
  eventName: "DWELL 2026: ELOHIM",
  eventSlug: "dwell-2026",
  eventDate: "Friday, August 28, 2026",
  eventTime: "6:00 PM CST",
  venue: "RCCG Jesus House Chicago",
  address: "5224 N. Kedzie Avenue\nChicago, IL 60625",
  registrationUrl: "https://thebridgechicago.org",
  canvasWidth: 1024,
  canvasHeight: 1536,
  artworkPath: "/event/dwell-2026-share-template.png",
  photoFrame: {
    x: 300,
    y: 607,
    width: 430,
    height: 528,
    cornerRadius: 54,
  },
  photo: {
    minimumZoom: 1,
    defaultZoom: 1,
    maximumZoom: 2.8,
  },
  name: {
    x: 512,
    y: 1195,
    maxWidth: 680,
    preferredFontSize: 56,
    minimumFontSize: 30,
    fontFamilyVariable: "--font-flyer",
    fallbackFontFamily: '"Arial Narrow", Impact, sans-serif',
    fontWeight: "700",
    uppercase: true,
    colour: "#fcd34d",
    textAlign: "center" as CanvasTextAlign,
  },
  message: {
    x: 512,
    y: 1260,
    maxWidth: 680,
    preferredFontSize: 28,
    minimumFontSize: 20,
    fontFamilyVariable: "--font-flyer",
    fallbackFontFamily: '"Arial Narrow", Arial, sans-serif',
    fontWeight: "600",
    uppercase: false,
    colour: "#ffffff",
    textAlign: "center" as CanvasTextAlign,
  },
  messages: [
    "I'll be attending!",
    "Join me at DWELL 2026.",
    "See you there!",
    "Don't miss it!",
    "Expecting an encounter.",
    "Be my guest.",
    "Let's worship together.",
  ],
  outputFilenamePrefix: "dwell-2026",
  nativeShareTitle: "DWELL 2026: ELOHIM",
  nativeShareText:
    "I’m attending DWELL 2026: ELOHIM with RCCG The Bridge Chicago. Join us on Friday, August 28, 2026 at 6:00 PM CST.",
  whatsappShareText:
    "I’m attending DWELL 2026: ELOHIM with RCCG The Bridge Chicago and City Shakers. Join us on Friday, August 28, 2026 at 6:00 PM CST. Register at https://thebridgechicago.org",
  pageTitle: "Create Your DWELL 2026 Flyer | RCCG The Bridge Chicago",
  pageDescription:
    "Add your name and photo to create your personalised “I’m Attending” flyer for DWELL 2026: ELOHIM.",
  privacyMessage:
    "Your photo is processed in your browser and is not uploaded or stored.",
  poweredBy: {
    text: "Powered by Velra",
    url: "https://velra.co.uk",
  },
  publicSiteUrl:
    process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  maxNameLength: 60,
  maxFileSizeBytes: 12 * 1024 * 1024,
} as const;

export type FlyerConfig = typeof flyerConfig;
